---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assign
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-full
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-full-binding
  namespace: default
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-full # name of role
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: assign # service account to bind to
  namespace: default # ns of service account
